# Generated by Django 5.2.15 on 2026-07-07 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_employee_face_embedding_employee_face_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('photographer_unit_price', models.DecimalField(decimal_places=2, help_text='Price per photo for photographers.', max_digits=10)),
                ('clown_unit_price', models.DecimalField(decimal_places=2, help_text='Price per photo for clowns.', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_workdays', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workdays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=150, null=True)),
                ('team_photo_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clown', models.ForeignKey(limit_choices_to={'role': 'clown'}, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_clown', to='employees.employee')),
                ('photographer', models.ForeignKey(limit_choices_to={'role': 'photographer'}, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_photographer', to='employees.employee')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='daily_sessions.workday')),
            ],
            options={
                'ordering': ['-work_day__date', 'team_name'],
                'unique_together': {('work_day', 'clown'), ('work_day', 'photographer')},
            },
        ),
        migrations.CreateModel(
            name='DailyOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=150)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='daily_sessions.workday')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyEmployeePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('adjustment_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='employees.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='daily_sessions.dailyteam')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='daily_sessions.workday')),
            ],
            options={
                'ordering': ['-work_day__date', 'employee__first_name'],
                'unique_together': {('work_day', 'employee')},
            },
        ),
    ]
