# Generated by Django 4.2.10 on 2026-07-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='status',
        ),
    ]
