# Generated by Django 5.2.15 on 2026-07-19 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0002_remove_workday_status'),
        ('employees', '0005_advance_bonus_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDailyOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_daily_operations', to='employees.employee')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_daily_operations', to='daily_sessions.workday')),
            ],
            options={
                'ordering': ['-work_day__date', 'seller__first_name'],
                'unique_together': {('work_day', 'seller')},
            },
        ),
    ]
