# Generated by Django 4.2.10 on 2026-07-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0009_fix_workday_date_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sellerdailyoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='workday',
            constraint=models.UniqueConstraint(fields=('location', 'date'), name='unique_workday_location_date'),
        ),
    ]
