# Generated by Django 5.2.15 on 2026-08-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0010_unique_constraint_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='clown_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per photo for clowns.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workday',
            name='photographer_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per photo for photographers.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workday',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked')], default='draft', max_length=15),
        ),
    ]
