# Generated by Django 5.2.15 on 2026-08-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0011_alter_workday_clown_unit_price_and_more'),
        ('employees', '0006_employee_is_active_alter_advance_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyemployeeperformance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='dailyteam',
            name='clown',
            field=models.ForeignKey(limit_choices_to={'role': 'clown'}, on_delete=django.db.models.deletion.PROTECT, related_name='teams_as_clown', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='dailyteam',
            name='photographer',
            field=models.ForeignKey(limit_choices_to={'role': 'photographer'}, on_delete=django.db.models.deletion.PROTECT, related_name='teams_as_photographer', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='sellerdailyoperation',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.PROTECT, related_name='seller_daily_operations', to='employees.employee'),
        ),
    ]
