# Generated by Django 4.2.10 on 2026-08-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0012_alter_dailyemployeeperformance_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='dynamic_pricing_enabled',
            field=models.BooleanField(default=False, help_text='Whether dynamic photo unit pricing is active for this WorkDay.'),
        ),
        migrations.AddField(
            model_name='workday',
            name='high_clown_price',
            field=models.DecimalField(decimal_places=2, default=55, help_text='Clown unit price when total photos > high_photo_threshold.', max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='high_photo_threshold',
            field=models.PositiveIntegerField(default=80, help_text='Photo threshold for high volume pricing.'),
        ),
        migrations.AddField(
            model_name='workday',
            name='high_photographer_price',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Photographer unit price when total photos > high_photo_threshold.', max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='is_manually_overridden',
            field=models.BooleanField(default=False, help_text='Whether pricing has been manually overridden by admin.'),
        ),
        migrations.AddField(
            model_name='workday',
            name='low_clown_price',
            field=models.DecimalField(decimal_places=2, default=45, help_text='Clown unit price when total photos < low_photo_threshold.', max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='low_photo_threshold',
            field=models.PositiveIntegerField(default=40, help_text='Photo threshold for low volume pricing.'),
        ),
        migrations.AddField(
            model_name='workday',
            name='low_photographer_price',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Photographer unit price when total photos < low_photo_threshold.', max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='override_clown_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually overridden clown unit price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='override_photographer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually overridden photographer unit price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='clown_unit_price',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Price per photo for clowns (Normal price).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workday',
            name='photographer_unit_price',
            field=models.DecimalField(decimal_places=2, default=45, help_text='Price per photo for photographers (Normal price).', max_digits=10),
        ),
    ]
