# Generated by Django 4.2.10 on 2026-08-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0013_workday_dynamic_pricing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='high_tier_active',
            field=models.BooleanField(default=True, help_text='Whether high volume pricing tier is active.'),
        ),
        migrations.AddField(
            model_name='workday',
            name='low_tier_active',
            field=models.BooleanField(default=True, help_text='Whether low volume pricing tier is active.'),
        ),
        migrations.AddField(
            model_name='workday',
            name='normal_tier_active',
            field=models.BooleanField(default=True, help_text='Whether normal volume pricing tier is active.'),
        ),
    ]
