# Generated by Django 4.2.10 on 2026-08-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sessions', '0014_workday_high_tier_active_workday_low_tier_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdailyoperation',
            name='rating',
            field=models.CharField(
                blank=True,
                choices=[
                    ('A++', 'A++'),
                    ('A+', 'A+'),
                    ('A', 'A'),
                    ('B', 'B'),
                    ('C', 'C'),
                    ('D', 'D'),
                    ('E', 'E'),
                    ('F', 'F'),
                ],
                help_text='Manual daily seller performance rating (A++ to F).',
                max_length=5,
                null=True,
            ),
        ),
    ]
