# Generated by Django 5.2.15 on 2026-06-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('photographer', 'Photographer'), ('seller', 'Seller'), ('clown', 'Clown')], default='admin', max_length=20),
        ),
    ]
