# Generated by Django 4.2.10 on 2026-07-01 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(help_text='Time work officially starts (e.g., 09:00:00)')),
                ('grace_period_minutes', models.PositiveIntegerField(default=5, help_text='Minutes after start time before employee is considered late')),
                ('maximum_late_minutes', models.PositiveIntegerField(default=60, help_text='Maximum allowed lateness before marked absent or penalized further')),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to deduct for lateness', max_digits=10)),
                ('attendance_enabled', models.BooleanField(default=True, help_text='Is the attendance system currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Cryptographically secure random token', max_length=255, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField()),
                ('session_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed (e.g., 'scan_qr', 'manual_update')", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Admin who performed the action, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_activity_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('minutes_late', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], max_length=50)),
                ('manual_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
