# Generated by Django 4.2.10 on 2026-07-02 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='override_reason',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='attendancerule',
            old_name='late_deduction',
            new_name='late_deduction_amount',
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='action',
            field=models.CharField(help_text="Action performed (e.g., 'fingerprint_enrolled', 'manual_attendance_created')", max_length=255),
        ),
        # Convert AttendanceLog.id from BigAutoField (bigint) to UUIDField.
        # PostgreSQL cannot directly cast bigint to uuid, so we drop the old
        # column and add a new UUID primary key.
        migrations.RunSQL(
            sql=[
                # Drop the old bigint primary key
                'ALTER TABLE "attendance_attendancelog" DROP CONSTRAINT "attendance_attendancelog_pkey";',
                'ALTER TABLE "attendance_attendancelog" DROP COLUMN "id";',
                # Add a new UUID primary key with defaults
                'ALTER TABLE "attendance_attendancelog" ADD COLUMN "id" uuid NOT NULL DEFAULT gen_random_uuid();',
                'ALTER TABLE "attendance_attendancelog" ADD CONSTRAINT "attendance_attendancelog_pkey" PRIMARY KEY ("id");',
            ],
            reverse_sql=[
                'ALTER TABLE "attendance_attendancelog" DROP CONSTRAINT "attendance_attendancelog_pkey";',
                'ALTER TABLE "attendance_attendancelog" DROP COLUMN "id";',
                'ALTER TABLE "attendance_attendancelog" ADD COLUMN "id" bigserial NOT NULL;',
                'ALTER TABLE "attendance_attendancelog" ADD CONSTRAINT "attendance_attendancelog_pkey" PRIMARY KEY ("id");',
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='attendancelog',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_record_per_employee_day'),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='manual_override',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='session',
        ),
    ]
