# Generated by Django 4.2.10 on 2026-07-02 00:33
# Modified to be idempotent (MySQL/MariaDB compatible — safe to re-run on
# a partially-migrated database).

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion
import uuid


def get_columns(table):
    """Return a set of column names for the given table."""
    with connection.cursor() as cursor:
        cursor.execute(f"SHOW COLUMNS FROM `{table}`;")
        return {row[0] for row in cursor.fetchall()}


def rename_override_reason(apps, schema_editor):
    cols = get_columns('attendance_attendancerecord')
    if 'override_reason' in cols and 'notes' not in cols:
        schema_editor.execute(
            'ALTER TABLE `attendance_attendancerecord` CHANGE `override_reason` `notes` longtext NOT NULL;'
        )


def rename_late_deduction(apps, schema_editor):
    cols = get_columns('attendance_attendancerule')
    if 'late_deduction' in cols and 'late_deduction_amount' not in cols:
        schema_editor.execute(
            'ALTER TABLE `attendance_attendancerule` CHANGE `late_deduction` `late_deduction_amount` decimal(10,2) NOT NULL;'
        )


def add_recorded_by(apps, schema_editor):
    cols = get_columns('attendance_attendancerecord')
    if 'recorded_by_id' not in cols:
        schema_editor.execute(
            'ALTER TABLE `attendance_attendancerecord` ADD COLUMN `recorded_by_id` integer NULL;'
        )


def remove_manual_override(apps, schema_editor):
    cols = get_columns('attendance_attendancerecord')
    if 'manual_override' in cols:
        schema_editor.execute(
            'ALTER TABLE `attendance_attendancerecord` DROP COLUMN `manual_override`;'
        )


def remove_session(apps, schema_editor):
    cols = get_columns('attendance_attendancerecord')
    if 'session_id' in cols:
        schema_editor.execute(
            'ALTER TABLE `attendance_attendancerecord` DROP COLUMN `session_id`;'
        )


def upgrade_attendancelog_id(apps, schema_editor):
    """Convert attendance_attendancelog.id from BigAutoField to UUIDField."""
    with connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM `attendance_attendancelog` LIKE 'id';")
        row = cursor.fetchone()
        if row is None:
            return
        col_type = row[1].lower()  # e.g. 'bigint(20)' or 'varchar(32)'
        if 'bigint' in col_type or 'int' in col_type:
            # Drop primary key, change column to UUID
            schema_editor.execute(
                'ALTER TABLE `attendance_attendancelog` DROP PRIMARY KEY;'
            )
            schema_editor.execute(
                "ALTER TABLE `attendance_attendancelog` "
                "CHANGE `id` `id` varchar(32) NOT NULL DEFAULT '';"
            )
            # Fill existing rows (there should be none on a fresh DB)
            cursor.execute(
                "UPDATE `attendance_attendancelog` SET `id` = REPLACE(UUID(), '-', '') WHERE `id` = '' OR `id` = '0';"
            )
            schema_editor.execute(
                'ALTER TABLE `attendance_attendancelog` ADD PRIMARY KEY (`id`);'
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        # Step 1: rename override_reason -> notes (idempotent)
        migrations.RunPython(rename_override_reason, migrations.RunPython.noop),

        # Step 2: rename late_deduction -> late_deduction_amount (idempotent)
        migrations.RunPython(rename_late_deduction, migrations.RunPython.noop),

        # Step 3: clear unique_together (state only — already gone in DB)
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),

        # Step 4: add recorded_by FK column (idempotent)
        migrations.RunPython(add_recorded_by, migrations.RunPython.noop),

        # Step 5: update action field max_length (pure state + safe ALTER)
        migrations.AlterField(
            model_name='attendancelog',
            name='action',
            field=models.CharField(
                help_text="Action performed (e.g., 'fingerprint_enrolled', 'manual_attendance_created')",
                max_length=255,
            ),
        ),

        # Step 6: upgrade id to UUID (idempotent)
        migrations.RunPython(upgrade_attendancelog_id, migrations.RunPython.noop),

        # Update Django's internal state to know id is now a UUIDField
        migrations.AlterField(
            model_name='attendancelog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

        # Step 7: add unique constraint
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(
                fields=('employee', 'date'),
                name='unique_attendance_record_per_employee_day',
            ),
        ),

        # Step 8: remove manual_override column (idempotent)
        migrations.RunPython(remove_manual_override, migrations.RunPython.noop),

        # Step 9: remove session column (idempotent)
        migrations.RunPython(remove_session, migrations.RunPython.noop),
    ]
