# Generated by Django 5.2.15 on 2026-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_override_reason_attendancerecord_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='allow_multiple_face_detection',
            field=models.BooleanField(default=False, help_text='Recognize multiple visible faces in a single frame.'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='attendance_method',
            field=models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face Recognition')], default='fingerprint', help_text='Selected attendance acquisition method.', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='camera_auto_start',
            field=models.BooleanField(default=False, help_text='Automatically start the camera when attendance is enabled.'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='camera_enabled',
            field=models.BooleanField(default=False, help_text='Whether the camera subsystem is enabled.'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='camera_fps',
            field=models.PositiveIntegerField(default=30, help_text='Target camera frame rate.'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='camera_index',
            field=models.PositiveIntegerField(default=0, help_text='Local camera index used by the backend.'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='camera_resolution',
            field=models.CharField(default='1280x720', help_text='Camera resolution in WIDTHxHEIGHT format.', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='face_confidence_threshold',
            field=models.FloatField(default=0.65, help_text='Minimum confidence required to accept a face match.'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='face_recognition_enabled',
            field=models.BooleanField(default=False, help_text='Enable face recognition within the attendance service.'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='recognition_cooldown_seconds',
            field=models.PositiveIntegerField(default=5, help_text='Cooldown period before the same employee can be recognized again.'),
        ),
    ]
