# Generated by Django 5.2.15 on 2026-07-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerule_allow_multiple_face_detection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerule',
            name='camera_auto_start',
            field=models.BooleanField(default=True, help_text='Automatically start the camera when attendance is enabled.'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='camera_enabled',
            field=models.BooleanField(default=True, help_text='Whether the camera subsystem is enabled.'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='face_recognition_enabled',
            field=models.BooleanField(default=True, help_text='Enable face recognition within the attendance service.'),
        ),
    ]
