# Generated by Django 5.2.15 on 2026-08-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerule_camera_auto_start_and_more'),
        ('employees', '0006_employee_is_active_alter_advance_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee'),
        ),
    ]
