# Generated by Django 5.2.15 on 2026-06-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('seller', 'Seller'), ('clown', 'Clown')], max_length=50),
        ),
    ]
