# Generated by Django 4.2.10 on 2026-07-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fingerprint_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='fingerprint_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fingerprint_template_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
