# Generated by Django 5.2.15 on 2026-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_fingerprint_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
