# Generated by Django 5.2.15 on 2026-08-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_advance_bonus_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='employees.employee'),
        ),
    ]
